### ISSUE TITLE
Can this plugin be used with tsup ?

### ISSUE THREAD

**Issue by dhowe** [Inqnuam/esbuild-plugin-umd-wrapper#1]
Wondering if  this plugin can be used with tsup ?

**Comment by Inqnuam** [comment]
Just tried it and it doesn't works out of box as esbuild-plugin-umd-wrapper requires  'format' to be "umd" which tsup simply ignores.

I just released 2.0.0 which fix this issue
here is an example to use it with tsup:

```js
const tsup = require("tsup"); // or import tsup from "tsup"
const { umdWrapper } = require("esbuild-plugin-umd-wrapper"); // or import { umdWrapper } from "esbuild-plugin-umd-wrapper"

tsup.build({
  esbuildPlugins: [umdWrapper()],
  entry: ["./index.ts"],
});

```

Thanks for reporting.

**Comment by dhowe** [comment]
Interesting, I still get an error when I try to use it with `defineConfig`:

<img width="452" alt="Screenshot 2023-11-13 at 10 09 55 PM" src="https://github.com/Inqnuam/esbuild-plugin-umd-wrapper/assets/737638/ad672bea-2e14-4ee8-9d40-fea5179c719e">
